config/routes.rb
Rails.application.routes.draw do
  resources :contactenos

  get 'juegos/sociales'

  get 'juegos/ingles'

  get 'juegos/espanol'

  get 'juegos/index'

  get 'juegos/sociales_nivel_1'

  get 'juegos/sociales_nivel_2'

  get 'juegos/ingles_nivel_1'

  get 'juegos/ingles_nivel_2'

  get 'juegos/espanol_nilvel_1'

  get 'juegos/espanol_nilvel_2'

  get 'juegos/biblioteca'

  get 'juegos/espacial'

  get 'juegos/playero'

  resources :galerias

  get 'bienvenido/index'
  
  get 'bienvenido/quienessomos'

  devise_for :usuarios

    root 'bienvenido#index'

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
    belongs_to :usuario
end

app/models/galeria.rb
class Galeria < ActiveRecord::Base
    has_attached_file :avatar, styles: { medium: '200x200>', thumb: '48x48>' }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :contactenos       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  before_action :authenticate_usuario!
  
  def index
  end
  
  def quienessomos
    
  end
  

  
end

app/controllers/contactenos_controller.rb
class ContactenosController < ApplicationController
  before_action :set_contacto, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @contactenos = Contacto.all
    respond_with(@contactenos)
  end
  
 

  def show
    respond_with(@contacto)
  end

  def new
    @contacto = Contacto.new
    respond_with(@contacto)
  end

  def edit
  end

  def create
    @contacto = Contacto.new(contacto_params)
    @contacto.save
    respond_with(@contacto)
  end

  def update
    @contacto.update(contacto_params)
    respond_with(@contacto)
  end

  def destroy
    @contacto.destroy
    respond_with(@contacto)
  end

  private
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    def contacto_params
      params.require(:contacto).permit(:nombre, :descripcion)
    end
end

app/controllers/galerias_controller.rb
class GaleriasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_galeria, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @galerias = Galeria.all
    respond_with(@galerias)
  end

  def show
    respond_with(@galeria)
  end

  def new
    @galeria = Galeria.new
    respond_with(@galeria)
  end

  def edit
  end

  def create
    @galeria = Galeria.create(galeria_params)
    @galeria.save
    respond_with(@galeria)
  end

  def update
    @galeria.update(galeria_params)
    respond_with(@galeria)
  end

  def destroy
    @galeria.destroy
    respond_with(@galeria)
  end

  private
    def set_galeria
      @galeria = Galeria.find(params[:id])
    end

    def galeria_params
      params.require(:galeria).permit(:titulo, :descripcion, :avatar)
    end
end

app/controllers/juegos_controller.rb
class JuegosController < ApplicationController
  def index
  end

  def sociales
  end

  def sociales_nivel_1
    
  end

  def sociales_nivel_2
  end

  def ingles
  end

  def ingles_nivel_1
  end

  def ingles_nivel_2
  end

  def espanol
  end

  def espanol_nilvel_1
  end

  def espanol_nilvel_2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/contactenos_helper.rb
module ContactenosHelper
end

app/helpers/galerias_helper.rb
module GaleriasHelper
end

app/helpers/juegos_helper.rb
module JuegosHelper
end

app/views/bienvenido/index.html.erb
<body class="fondo">
   
<br>


<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("1.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("3.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
   <div class="item">
      <%= image_tag("2.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

   
</body>

app/views/bienvenido/quienessomos.html.erb
<body class="fondo">
    
    <br>
       <div class="jumbotron">
           <div class="container">
               <div class="med">
                   
                 <h1 class="white1">
                     EUREKA
                 </h1>
                    
                <h5>Somos una pagina web, dedicada a ofrecer el servicio de aprendizaje facilitando al púbico el acceso a herramientas virtuales para fortalecer y mejorar
                el nivel educativo local y Regional, por medio de EUREKA, una pagina web interactiva. </h5>
                <h5>Nuestra misión es ser un apoyo fundamental en la educación y valores, e instruir a los niños para utilizar herramientas y tecnologías mas alla
                del entretenimiento personal, Para el año 2020, seremos un apoyo indispensable para la educación primaria a nivel nacional, mejorando los niveles académicos y expandiéndolos a la 
                educación secundaria</h5>
                <p>
                <br>
                <%= image_tag("22.jpg", class:'img-circle social1' ) %>
                <%= image_tag("11.jpg", class:'img-circle social1')  %>
                <%= image_tag("33.jpg", class:'img-circle social1' ) %>
                <%= image_tag("44.jpg", class:'img-circle social1')  %>
                </p>
        </div> 
           </div>
       </div>
        
    
    
</body>

app/views/contactenos/_form.html.erb
<div class="">
  <%= form_for(@contacto) do |f| %>
  <% if @contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contacto.errors.count, "error") %> prohibited this contacto from being saved:</h2>

      <ul>
      <% @contacto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h5 class="white1">Nombre</h5>
    <%= f.text_field :nombre, class:'form-control' %>
  </div>
  <div class="field">
    <h5 class="white1">Descripción</h5>
    <%= f.text_area :descripcion, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit"Agregar",class:'btn btn-default btn-lg btn-block' %>
  </div>
<% end %>

</div>

app/views/contactenos/edit.html.erb
<h1>Editing contacto</h1>

<%= render 'form' %>

<%= link_to 'Show', @contacto %> |
<%= link_to 'Back', contactenos_path %>

app/views/contactenos/index.html.erb
<body class="fondo">
  


</body>



<% if current_usuario == Usuario.find(1) %>
<%= link_to "<i class='fa fa-plus fa-3x'></i>".html_safe,  new_contacto_path %>
<table class="table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contactenos.each do |contacto| %>
      <tr>
        <td><%= contacto.nombre %></td>
        <td><%= contacto.descripcion %></td>
        <td></td>
        <td><%= link_to 'Edit', edit_contacto_path(contacto) %></td>
        <td><%= link_to 'Destroy', contacto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% elsif%>

  <br> </br>

    <div class="jumbotron1">
 
<h1>
<%= link_to image_tag('eureka.png',class:'img-responsive eve',).html_safe,  new_contacto_path %>

<h2 class="white11">Contactenos</h2>

<br></h1>
   
</div>
<%end%>

app/views/contactenos/new.html.erb
<body class="fondo">
    <br></br>
     <br></br>

    <div class="col-md-12">
    <div class="col-md-3"></div>
    <div class="col-md-6 jumbotron">
        
<%= render 'form' %>


        
    </div>
    <div class="col-md-3"></div>
</div>

</body>

app/views/contactenos/show.html.erb
<p id="notice"><%= notice %></p>


<body class="fondo">
  
  <br> </br>

    <div class="jumbotron1">
 
<h1>
<%= link_to image_tag('eureka.png',class:'img-responsive eve',).html_safe,  new_contacto_path %>

<h5 class="white111">Agradecemos su contacto y pronto nos comunicaremos</h5>
<h4 class="white1111">
  <strong><%= @contacto.nombre %></strong> 
</h4>

</h1>
</div>

</body>

app/views/galerias/_form.html.erb
    <%= form_for @galeria, html: { multipart: true } do |f| %>
  <% if @galeria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galeria.errors.count, "error") %> prohibited this galeria from being saved:</h2>

      <ul>
      <% @galeria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="formulario">
  
  <div class="field">
    <h5 class="white1">Título</h5>
    <%= f.text_field :titulo, class:'form-control' %>
  </div>
   <div class="field">
    <h5 class="white1">Imagen</h5>
    <%= f.file_field :avatar, class:'form-control' %>
  </div>
  <div class="field">
    <h5 class="white1">Descripción</h5>
    <%= f.text_area :descripcion, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit"Guardar",class:'btn btn-default btn-lg btn-block' %>
  </div>
</div>
<% end %>



<style>
  .formulario{
  h5{
     font-weight: bold;
     color: white;
     font-size: 20px;
  }
}
</style>

app/views/galerias/edit.html.erb
<body class="fondo">
<div class="col-md-12">
    
    <div class="col-md-3"></div>
    <div class="col-md-6">
       <div class="jumbotron">
            <h1 class="white">Editar</h1>

<%= render 'form' %>

<%= link_to "<i class='fa fa-camera-retro fa-3x'></i>".html_safe, @galeria %> |
<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, galerias_path %>
   
       </div>    
       
    </div>
    <div class="col-md-3"></div>
    
</div>

</body>

app/views/galerias/index.html.erb
<body class="fondo">
  

<div class="container">
  <div class="row">
    <h2>Galería de Imagenes</h2>
    
    <% if current_usuario == Usuario.find(1) %>
    <%= link_to "<i class='fa fa-plus fa-3x'></i>".html_safe, new_galeria_path %>
    <% end %>
    </p>
    <hr>
    <section id="pinBoot">
      <% @galerias.each do |galeria| %>

      <article class="white-panel"><%= image_tag galeria.avatar.url(), class:'img1' %>
        <h4><%= galeria.titulo %></h4>
        <p><%= galeria.descripcion %></p>
        <td><%= link_to "<i class='fa fa-file-image-o fa-3x social1'></i>".html_safe, galeria %></td>
        
      </article>

     
     <% end %>
    </section>


    <hr>


  </div>
 
</div>
</body>

app/views/galerias/new.html.erb
<body class="fondo">
    <br></br>
<div class="col-md-12">
    <div class="col-md-3"></div>
    <div class="col-md-6">
    <div class="jumbotron">
                
    <h1 class="white1">Nueva</h1>

<%= render 'form' %>

<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, galerias_path %>
        
    </div>
    </div>
    <div class="col-md-3"></div>
    
</div>

</body>

app/views/galerias/show.html.erb
<body class="fondo">
  <p id="notice"><%= notice %></p>



<div id="gurney_hallek_profile_card" class="card">
  <div class="wall-container">
    <%= image_tag @galeria.avatar.url(), class:' wall-pic img-responsive' %>
  </div>
  <div class="profile" >
   <div class="profile-pic-border">
    <%= image_tag("lobo.jpg", class:'profile-pic ') %>
    </div>
    <h2>  <strong>Titulo:</strong>
  <%= @galeria.titulo %> </h2>
    <p><strong>Descripcion:</strong>
  <%= @galeria.descripcion %> </p>
  </div>
  
</div>


<%= link_to "<i class='fa fa-folder-open-o fa-3x social1'></i>".html_safe, galerias_path %>

</body>





<style>
  body {
background-image: linear-gradient(right bottom, rgb(225,197,185) 17%, rgb(194,128,112) 91%);
background-image: -o-linear-gradient(right bottom, rgb(225,197,185) 17%, rgb(194,128,112) 91%);
background-image: -moz-linear-gradient(right bottom, rgb(225,197,185) 17%, rgb(194,128,112) 91%);
background-image: -webkit-linear-gradient(right bottom, rgb(225,197,185) 17%, rgb(194,128,112) 91%);
background-image: -ms-linear-gradient(right bottom, rgb(225,197,185) 17%, rgb(194,128,112) 91%);

background-image: -webkit-gradient(
	linear,
	right bottom,
	left top,
	color-stop(0.17, rgb(225,197,185)),
	color-stop(0.91, rgb(194,128,112))
);
  min-height: 100%;
}


.card {
  border-radius: 8px;
  background-color: white;
  margin: 1% auto;
  overflow: hidden;
  width: 800px;
}

.wall-container {
  height: 400px;
  overflow: hidden;
}

.wall-pic {
  border-radius: 8px 8px 0 0;
  width: 100%;
  height:100%;
}

.profile {
  border-width: 1px 0 0 0;
  border-style: solid;
  border-color: #454545;
  height: 100px;
  padding: 20px;
}

.profile h2 {
  color: #776B5F;
  font: 28px/30px Helvetica, sans-serif;
  font-weight: bold;
  margin: 5px 0 10px 0;
  padding: 0;
  text-transform: capitalize;
}

.profile p {
  color: #776B5F;
  font: 14px/16px Helvetica, sans-serif;
  margin: 0;
  padding: 0;
  width: 100%;
}

.profile-pic-border{
    border: 1px solid #B7AEA4;
    border-radius: 50%;
    float: left;
    height: 85px;
    margin: 0 20px 0 0;
    width: 85px;
}

.profile-pic {
   border: 5px solid #fff;
   border-radius: 50%;
   height: 75px;
   width: 75px;
}

.social-container {
  height: 50px;
}

.social {
  box-sizing: border-box;
  background-color: #f6f1ed;
  float: left;
  height: 50px;
  padding: 0 0 0 40px;
  width: 33%;
}

.social-icon {
  color: #b1a599;
  float: left;
  font-family: 'RaphaelIcons';
  font-size: 30px;
  font-weight: 300;
  line-height: 18px;
  margin: 0 8px 0 0;
}

.social p {
  color: #b1a599;
  font: 18px/18px Helvetica, sans-serif;
  font-weight: bold;
}

.middle {
  margin: 0 2px 0 2px;
}
</style>




<script>

$('.social1').mouseenter( function() {
  $( this ).animate({
    'margin-top': '-10px'
  }, 100,  function () {
   $( this ).animate({
    'margin-top': '0px'
    });
  });
});


  $('.social').mouseenter( function() {
  $( this ).animate({
    'margin-top': '-10px'
  }, 100,  function () {
   $( this ).animate({
    'margin-top': '0px'
    });
  });
});

$('.profile-pic').mouseenter ( function() {
  $(this).animate ( {
      'margin' : '8px',
      'width': '60px',
      'height': '60px' 
  }, 300, function () {
    $(this).animate ( {
      'margin' : '0px',
      'width': '75px',
      'height': '75px' 
    });
  });
});
</script>

app/views/juegos/espanol.html.erb
<body class="fondo">
    
  <br></br><br></br>



<div class="col-md-12">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="jumbotron">
              <h1 class="white1">Español</h1>
            
<%= link_to "Nivel 1", juegos_espanol_nilvel_1_path, class:'btn btn-default btn-lg btn-block' %>
<%= link_to "Nivel 2", juegos_espanol_nilvel_2_path, class:'btn btn-default btn-lg btn-block' %>

        </div>
    </div>
    <div class="col-md-3"></div>
    
</div>



<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_index_path %>

</body>

app/views/juegos/espanol_nilvel_1.html.erb
<body class="fondo">
    <br></br><br></br>

<div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-4">    
<%= swf_tag "espanol1.swf", class:'sociales1' %>
</div>
<div class="col-md-2"></div>
</div>


<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_espanol_path %>


</body>

app/views/juegos/espanol_nilvel_2.html.erb
<body class="fondo">
    <br></br><br></br>

<div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-4">    
<%= swf_tag "espanol2.swf", class:'sociales1' %>
</div>
<div class="col-md-2"></div>
</div>


<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_espanol_path %>


</body>

app/views/juegos/index.html.erb
<body class="fondo">
<br></br>

<h1 class="center">JUEGOS</h1>




<div class="col-md-12 jumbotron">
    
   

<div class="col-md-4">
    
<span><h2>
<%=link_to " <h1 class='ss'>Sociales</h1> ".html_safe, juegos_sociales_path, class:'button'%></h2></span>

</div>
 <div class="col-md-4">
     <h1>
    
<span><h2>
<%=link_to " <h1 class='ss'>Inglés</h1> ".html_safe, juegos_ingles_path, class:'button'%></h2></span>
</h1>
     
 </div>
  <div class="col-md-4">
  
<span><h2>
<%=link_to " <h1 class='ss'>Español</h1> ".html_safe, juegos_espanol_path, class:'button'%></h2></span>
  </div>

    
</div>



</body>

app/views/juegos/ingles.html.erb
<body class="fondo">
    
  <br></br><br></br>



<div class="col-md-12">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="jumbotron">
              <h1 class="white1">Inglés</h1>
            
<%= link_to "Nivel 1", juegos_ingles_nivel_1_path, class:'btn btn-default btn-lg btn-block' %>
<%= link_to "Nivel 2", juegos_ingles_nivel_2_path, class:'btn btn-default btn-lg btn-block' %>

        </div>
    </div>
    <div class="col-md-3"></div>
    
</div>



<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_index_path %>

</body>

app/views/juegos/ingles_nivel_1.html.erb
<body class="fondo">
    <br></br><br></br>

<div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-4 ">    
<%= swf_tag "playero.swf", class:'sociales1' %>
</div>
<div class="col-md-2"></div>
</div>


<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_ingles_path %>


</body>


<script>
    


$(document).ready(function () {
    $(".sociales1").swfobject();
});

</script>

app/views/juegos/ingles_nivel_2.html.erb
<body class="fondo">
    <br></br><br></br>

<div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-4">    
<%= swf_tag "cirquero.swf", class:'sociales1' %>
</div>
<div class="col-md-2"></div>
</div>


<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_ingles_path %>


</body>

app/views/juegos/sociales.html.erb
<body class="fondo">
    
  <br></br><br></br>



<div class="col-md-12">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="jumbotron">
              <h1 class="white1">Sociales</h1>
            
<%= link_to "Nivel 1", juegos_sociales_nivel_1_path, class:'btn btn-default btn-lg btn-block' %>
<%= link_to "Nivel 2", juegos_sociales_nivel_2_path, class:'btn btn-default btn-lg btn-block' %>

        </div>
    </div>
    <div class="col-md-3"></div>
    
</div>



<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_index_path %>

</body>

app/views/juegos/sociales_nivel_1.html.erb
<body class="fondo">
    <br></br><br></br>

<div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-4">    
<%= swf_tag "sociales.swf", class:'sociales1' %>
</div>
<div class="col-md-2"></div>
</div>


<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_sociales_path %>


</body>

app/views/juegos/sociales_nivel_2.html.erb
<body class="fondo">
    <br></br><br></br>

<div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-4">    
<%= swf_tag "sociales1.swf", class:'sociales1' %>
</div>
<div class="col-md-2"></div>
</div>


<%= link_to "<i class='fa fa-arrow-left fa-3x'></i>".html_safe, juegos_sociales_path %>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EUREKA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <% if usuario_signed_in? %>
    
    

<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	 <a class="navbar-brand" href="#">
        <%= image_tag("logoeurek.png") %>
       
      </a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
			
			<li class="barra1"><h4><%=link_to "Inicio", root_path%></h4></li>
			
			<li class="barra1"><h4><%= link_to "Galería", galerias_path  %></h4></li>
			
			<li class="barra1"><h4><%= link_to "Juegos", juegos_index_path  %></h4></li>
				
			<li class="barra1"><h4><%=link_to "Quíenes Somos", bienvenido_quienessomos_path%></h4></li>
			
			<li class="barra1"><h4><%=link_to "Contactenos", contactenos_path%></h4></li>
			

		</ul>
	
		<ul class="nav navbar-nav navbar-right">
			
      
			<li><%= link_to "<i class='fa fa-user-times fa-2x'></i>".html_safe, destroy_usuario_session_path, :method => :delete, class: 'active' %></li>
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>
    
    <% end %>
    
	    <style>
	    
	    	.barra1{
	    		padding: 2px 7px;
	    	}
	    	
	    </style>
    
    

<div class="container">
    <div class="row">
        

<%= yield %>

        
    </div>
</div>
</body>
</html>